# Generated by Django 4.2.21 on 2025-05-11 07:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildablePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('section', 12)], block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 12}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StreamBlock', [[('image', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('n_column_filled', 1), ('images', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('n_column_filled', 1), ('rich_text', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('n_column_filled', 1)]], {}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 3}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('list', 'List'), ('horizontal_scrolling_cards', 'Horizontal Scrolling Cards')]}), 10: ('wagtail.blocks.StructBlock', [[('n_column_filled', 1), ('number_of_articles', 8), ('style', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('images', 4), ('rich_text', 6), ('contact_form', 7), ('latest_articles', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('add_container', 0), ('add_vertical_padding', 0), ('children', 11)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
